server:
  port: 8080

app-config:
  github:
    api-url: https://api.github.com
    repositories-path: "/search/repositories"
    per-page: 100 # Hard limit by Github
    max-pages: 2 # Max hard limit by Github is 10
    parallelism: 10
  popularity-score-weights:
    stars: 0.6
    forks: 0.3

spring:
  application:
    name: github-repo-scorer
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=15m
  jackson:
        deserialization:
          fail-on-unknown-properties: false

logging:
  level:
    dev.yelpalekshitij: trace
